services:
  - type: web
    name: waste-paper-management
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true